# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
